import { Main } from "./src/ts/Main";
import { Addons } from "./src/ts/Utilities/Addons";
import { ArchiveHoverImage } from "./src/ts/Utilities/ArchiveHoverImage";
import { Cart } from "./src/ts/Utilities/Cart";
import { CategoryPagination } from "./src/ts/Utilities/CategoryPagination";
import { ChangeColorLabelOnVariationChange } from "./src/ts/Utilities/ChangeColorLabelOnVariationChange";
import { CommentsLoadMore } from "./src/ts/Utilities/CommentsLoadMore";
import { Context } from "./src/ts/Utilities/Context";
import { CustomFurniture } from "./src/ts/Utilities/CustomFurniture";
import { Facets } from "./src/ts/Utilities/Facets";
import { HideFurnitureVariationSwatches } from "./src/ts/Utilities/HideFurnitureVariationSwatches";
import { LandingGallery } from "./src/ts/Utilities/LandingGallery";
import { LeatherSample } from "./src/ts/Utilities/LeatherSample";
import { LeatherSampleForm } from "./src/ts/Utilities/LeatherSampleForm";
import { MobileMenu } from "./src/ts/Utilities/MobileMenu";
import { Modals } from "./src/ts/Utilities/Modals";
import { ProductQuantity } from "./src/ts/Utilities/ProductQuantity";
import { ProductStock } from "./src/ts/Utilities/ProductStock";
import { QuickviewPagination } from "./src/ts/Utilities/QuickviewPagination";
import { Serialize } from "./src/ts/Utilities/Serialize";
import { SimpleCarousel } from "./src/ts/Utilities/SimpleCarousel";
import { Slick } from "./src/ts/Utilities/Slick";
import { Tooltips } from "./src/ts/Utilities/Tooltips";
import { UnitType } from "./src/ts/Utilities/UnitType";
import { SiteSettings } from "./src/ts/Models/SiteSettings";
import { WordpressSettings } from "./src/ts/Models/WordpressSettings";
import { ActionSet } from "./src/ts/Base/ActionSet";
import { FrontPageActionSet } from "./src/ts/ActionSets/FrontPageActionSet";
import { GlobalActionSet } from "./src/ts/ActionSets/GlobalActionSet";
import { TemplateMonogramActionSet } from "./src/ts/ActionSets/TemplateMonogramActionSet";
import { WoocommerceActionSet } from "./src/ts/ActionSets/WoocommerceActionSet";
import { WoocommerceCartActionSet } from "./src/ts/ActionSets/WoocommerceCartActionSet";
import { WoocommerceCheckoutActionSet } from "./src/ts/ActionSets/WoocommerceCheckoutActionSet";
import { WoocommerceOrderReceivedActionSet } from "./src/ts/ActionSets/WoocommerceOrderReceivedActionSet";
import { WoocommerceSingleActionSet } from "./src/ts/ActionSets/WoocommerceSingleActionSet";

export let MooreAndGiles: any = {};

MooreAndGiles.Main = Main;
MooreAndGiles.Addons = Addons;
MooreAndGiles.ArchiveHoverImage = ArchiveHoverImage;
MooreAndGiles.Cart = Cart;
MooreAndGiles.CategoryPagination = CategoryPagination;
MooreAndGiles.ChangeColorLabelOnVariationChange = ChangeColorLabelOnVariationChange;
MooreAndGiles.CommentsLoadMore = CommentsLoadMore;
MooreAndGiles.Context = Context;
MooreAndGiles.CustomFurniture = CustomFurniture;
MooreAndGiles.Facets = Facets;
MooreAndGiles.HideFurnitureVariationSwatches = HideFurnitureVariationSwatches;
MooreAndGiles.LandingGallery = LandingGallery;
MooreAndGiles.LeatherSample = LeatherSample;
MooreAndGiles.LeatherSampleForm = LeatherSampleForm;
MooreAndGiles.MobileMenu = MobileMenu;
MooreAndGiles.Modals = Modals;
MooreAndGiles.ProductQuantity = ProductQuantity;
MooreAndGiles.ProductStock = ProductStock;
MooreAndGiles.QuickviewPagination = QuickviewPagination;
MooreAndGiles.Serialize = Serialize;
MooreAndGiles.SimpleCarousel = SimpleCarousel;
MooreAndGiles.Slick = Slick;
MooreAndGiles.Tooltips = Tooltips;
MooreAndGiles.UnitType = UnitType;
MooreAndGiles.SiteSettings = SiteSettings;
MooreAndGiles.WordpressSettings = WordpressSettings;
MooreAndGiles.ActionSet = ActionSet;
MooreAndGiles.FrontPageActionSet = FrontPageActionSet;
MooreAndGiles.GlobalActionSet = GlobalActionSet;
MooreAndGiles.TemplateMonogramActionSet = TemplateMonogramActionSet;
MooreAndGiles.WoocommerceActionSet = WoocommerceActionSet;
MooreAndGiles.WoocommerceCartActionSet = WoocommerceCartActionSet;
MooreAndGiles.WoocommerceCheckoutActionSet = WoocommerceCheckoutActionSet;
MooreAndGiles.WoocommerceOrderReceivedActionSet = WoocommerceOrderReceivedActionSet;
MooreAndGiles.WoocommerceSingleActionSet = WoocommerceSingleActionSet;